version: "3.7"

services:
  nsite:
    build: .
    image: ghcr.io/hzrd149/nsite-ts:master
    environment:
      LOOKUP_RELAYS: wss://user.kindpag.es,wss://purplepag.es
      SUBSCRIPTION_RELAYS: wss://nostrue.com/,wss://nos.lol/,wss://relay.damus.io/,wss://purplerelay.com/
    volumes:
      - type: tmpfs
        target: /var/cache/nginx
        tmpfs:
          size: 100M
    ports:
      - 8080:80
      - 3000:3000
